
title: My Resume
url: 'http://webjeda.com'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Francois D'Agostini
tagline: Software Technical lead and product manager 
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: francois.dagostini@gmail.com 
phone: +33 6 18 65 25 08
website: www.dagostini.fr #do not add http://
linkedin: fdagostini
github: fdagosti


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
